In [1]:
import pandas as pd
import glob
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

inn_1 = pd.read_csv('/Users/roumyadas/Desktop/Data/t20_cricket_data/Data/created_data/inn_1.csv')
inn_2 = pd.read_csv('/Users/roumyadas/Desktop/Data/t20_cricket_data/Data/created_data/inn_2.csv')
#inn_1_i = pd.read_csv('/Users/roumyadas/Desktop/Data/t20_cricket_data/Data/created_data/inn_1_i.csv')
#inn_2_i = pd.read_csv('/Users/roumyadas/Desktop/Data/t20_cricket_data/Data/created_data/inn_2_i.csv')

/Users/roumyadas/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (1,20,21) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
venues = []
col = 'venue'
dfs = [inn_1, inn_2]

for df in dfs:
    ls = df[col].unique().tolist()
    venues.append(ls)
    
venues_list = list(set(element for sublist in venues for element in sublist))

len(venues_list)

320

In [3]:
i=37

venues_list[i*10: (i+1)*10]

[]

In [4]:
ground_map = {'M Chinnaswamy Stadium, Bangalore':'RCB',
              'M.Chinnaswamy Stadium':'RCB',
              'M Chinnaswamy Stadium, Bengaluru':'RCB',
              
              'MA Chidambaram Stadium, Chepauk':'CSK',
              'MA Chidambaram Stadium, Chepauk, Chennai':'CSK',
              'MA Chidambaram Stadium':'CSK',
              
              'Arun Jaitley Stadium':'DC',
              'Arun Jaitley Stadium, Delhi':'DC',
              
              'Wankhede Stadium, Mumbai':'MI',
              'Wankhede Stadium':'MI',
              
              
              'Rajiv Gandhi International Stadium, Uppal, Hyderabad':'SRH',
              'Rajiv Gandhi International Stadium, Uppal':'SRH',
              'Rajiv Gandhi International Stadium':'SRH',
              
              'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow':'LSG',
              'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium':'LSG',
              
              'Eden Gardens, Kolkata':'KKR',
              'Eden Gardens':'KKR',
              
              'Narendra Modi Stadium, Ahmedabad':'GT',
              'Narendra Modi Stadium':'GT',
              
              'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur':'PBKS',
              
              'Sawai Mansingh Stadium, Jaipur':'RR',
              'Sawai Mansingh Stadium':'RR'
             
             }

In [5]:
for df in dfs:

    df['venue'] = df['venue'].replace(ground_map)

In [6]:
grounds = ['CSK','DC','GT','KKR','LSG','MI','PBKS','RCB','RR','SRH']

inn_1_g = inn_1[inn_1.venue.isin(grounds)]
inn_2_g = inn_2[inn_2.venue.isin(grounds)]
#inn_1_i_g = inn_1_i[inn_1_i.venue.isin(grounds)]
#inn_2_i_g = inn_2_i[inn_2_i.venue.isin(grounds)]

print(inn_1_g.shape, inn_2_g.shape)

(42998, 60) (39541, 60)

In [7]:
inn_1_g.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'year', 'legality', 'bowler_wicket',
       'islegal', 'isDotforBatter', 'isOne', 'isTwo', 'isThree',
       'isStrikeRotation', 'isFour', 'isSix', 'isBowlerWicket',
       'is_striker_Out', 'is_nonstriker_Out', 'isWicket', 'total_runs',
       'runs_scored', 'wickets_down', 'legal_balls_bowled', 'lbb_fl',
       'run_rate', 'target', 'legal_balls_remaining', 'runs_remaining',
       'reqd_run_rate', 'last_fow_run_rate', 'last_fow', 'partnership_runs',
       'striker_runs', 'non_striker_runs', 'isno', 'is_faced_by_batter',
       'striker_balls', 'non_striker_balls', 'fours', 'sixes',
       'striker_batting_position', 'non_striker_batting_position'],
      dtype='object')

In [8]:
df_g = inn_1_g

for df in [inn_2_g]:
    df_g = df_g.append(df)
   
df_g = df_g.sort_values(by=['match_id','start_date'])

df_g.shape

(82539, 60)

In [9]:
df_g.to_csv('/Users/roumyadas/Desktop/Data/t20_cricket_data/Data/created_data/t20_g.csv', index=None)

In [10]:
df_g.sample(10)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,year,legality,bowler_wicket,islegal,isDotforBatter,isOne,isTwo,isThree,isStrikeRotation,isFour,isSix,isBowlerWicket,is_striker_Out,is_nonstriker_Out,isWicket,total_runs,runs_scored,wickets_down,legal_balls_bowled,lbb_fl,run_rate,target,legal_balls_remaining,runs_remaining,reqd_run_rate,last_fow_run_rate,last_fow,partnership_runs,striker_runs,non_striker_runs,isno,is_faced_by_batter,striker_balls,non_striker_balls,fours,sixes,striker_batting_position,non_striker_batting_position
437635,1426275,2024,2024-04-21,PBKS,1,10.4,Punjab Kings,Gujarat Titans,Shashank Singh,JM Sharma,Noor Ahmad,1,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2024,True,False,1,0,1,0,0,1,0,0,0,0,0,0,1,79,4,64,True,7.406250,NaN,56,NaN,NaN,7.548387,78.0,123.0,1,6,False,True,2,7,8,3,6,4
317322,1359535,2023,2023-05-14,CSK,1,11.6,Chennai Super Kings,Kolkata Knight Riders,S Dube,RA Jadeja,Suyash Sharma,1,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2023,True,False,1,0,1,0,0,1,0,0,0,0,0,0,1,81,5,72,True,6.750000,NaN,48,NaN,NaN,6.545455,72.0,46.0,12,1,False,True,10,1,6,2,5,7
435857,1446102,2024/25,2024-12-11,RCB,2,12.2,Uttar Pradesh,Delhi,V Nigam,Sameer Rizvi,Harsh Tyagi,4,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2024,True,False,1,0,0,0,0,0,1,0,0,0,0,0,4,109,5,74,True,8.837838,194.0,46,85.0,11.086957,8.788732,104.0,92.0,4,17,False,True,2,11,12,3,7,6
123506,1280208,2021/22,2021-11-04,DC,2,17.7,Railways,Bihar,Himanshu Sangwan,T Pradeep,Hrishi Raj,1,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2021,True,False,1,0,1,0,0,1,0,0,0,0,0,0,1,134,9,107,True,7.514019,170.0,13,36.0,16.615385,7.384615,128.0,78.0,1,5,False,True,1,3,13,1,11,10
296149,1348651,2022/23,2023-02-01,GT,1,2.4,India,New Zealand,Shubman Gill,RA Tripathi,LH Ferguson,4,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2023,True,False,1,0,0,0,0,0,1,0,0,0,0,0,4,23,1,16,True,8.625000,NaN,104,NaN,NaN,5.250000,23.0,57.0,15,6,False,True,8,5,4,0,2,3
131306,1278673,2021/22,2021-11-21,KKR,1,1.5,India,New Zealand,Ishan Kishan,RG Sharma,AF Milne,2,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2021,True,False,1,0,0,1,0,1,0,0,0,0,0,0,2,14,0,11,True,7.636364,NaN,109,NaN,NaN,NaN,0.0,31.0,6,8,False,True,5,6,3,0,2,1
280923,1359480,2023,2023-04-03,CSK,2,12.3,Lucknow Super Giants,Chennai Super Kings,MP Stoinis,N Pooran,MJ Santner,0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2023,True,False,1,1,0,0,0,0,0,0,0,0,0,0,0,127,4,75,True,10.160000,218.0,45,91.0,12.133333,10.500000,105.0,82.0,18,17,False,True,14,8,12,5,5,6
54743,1244310,2020/21,2021-01-10,KKR,2,4.2,Jharkhand,Tamil Nadu,Utkarsh Singh,Kumar Deobrat,Sonu Yadav,0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2021,True,False,1,1,0,0,0,0,0,0,0,0,0,0,0,34,1,26,True,7.846154,190.0,94,156.0,9.957447,6.800000,34.0,0.0,10,11,False,True,7,11,6,0,3,1
539674,1473471,2025,2025-04-18,RCB,1,7.5,Royal Challengers Bengaluru,Punjab Kings,MS Bhandage,TH David,YS Chahal,0,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2025,True,False,1,1,0,0,0,0,0,0,0,0,0,0,0,41,6,47,True,5.234043,NaN,73,NaN,NaN,5.347826,41.0,102.0,0,6,False,True,1,6,4,1,8,7
538018,1473458,2025,2025-04-07,MI,1,1.5,Royal Challengers Bengaluru,Mumbai Indians,V Kohli,D Padikkal,DL Chahar,2,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2025,True,False,1,0,0,1,0,1,0,0,0,0,0,0,2,16,1,11,True,8.727273,NaN,109,NaN,NaN,12.000000,16.0,34.0,8,4,False,True,5,4,3,0,2,3

In [11]:
df_g.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'year', 'legality', 'bowler_wicket',
       'islegal', 'isDotforBatter', 'isOne', 'isTwo', 'isThree',
       'isStrikeRotation', 'isFour', 'isSix', 'isBowlerWicket',
       'is_striker_Out', 'is_nonstriker_Out', 'isWicket', 'total_runs',
       'runs_scored', 'wickets_down', 'legal_balls_bowled', 'lbb_fl',
       'run_rate', 'target', 'legal_balls_remaining', 'runs_remaining',
       'reqd_run_rate', 'last_fow_run_rate', 'last_fow', 'partnership_runs',
       'striker_runs', 'non_striker_runs', 'isno', 'is_faced_by_batter',
       'striker_balls', 'non_striker_balls', 'fours', 'sixes',
       'striker_batting_position', 'non_striker_batting_position'],
      dtype='object')